# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
license = "${mod_license}"
loaderVersion = "${forge_loader_version_range}"
issueTrackerURL = "${mod_issue_tracker_url}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
# updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "${mod_display_url}"
logoFile = "assets/skin_changer/logo.png"
# credits=""
authors = "${mod_authors}"
description = '''${mod_description}'''
displayTest = "MATCH_VERSION"          # MATCH_VERSION is the default if nothing is specified )

[[dependencies.skin_changer]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.skin_changer]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.skin_changer]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_version_range}"
ordering = "AFTER"
side = "BOTH"

[mc-publish]
dependencies = ["architectury-api(required){modrinth:lhGA9TYQ}{curseforge:419699}"]
