name: Publish on GitHub, CurseForge & Modrinth

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Extract versions from gradle.properties
              run: |
                  echo "MOD_VERSION=$(grep '^mod_version' gradle.properties | cut -d'=' -f2 | tr -d ' ')" >> $GITHUB_ENV
                  echo "MINECRAFT_VERSION=$(grep '^minecraft_version ' gradle.properties | cut -d'=' -f2 | tr -d ' ')" >> $GITHUB_ENV
                  echo "JAVA_VERSION=$(grep '^java_version' gradle.properties | cut -d'=' -f2 | tr -d ' ')" >> $GITHUB_ENV

            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  distribution: "temurin"
                  java-version: ${{ env.JAVA_VERSION }}

            - name: Make Gradle Wrapper Executable
              if: ${{ runner.os != 'Windows' }}
              run: chmod +x ./gradlew

            - name: Build
              run: ./gradlew clean build

            - name: Publish (GitHub)
              uses: Kir-Antipov/mc-publish@v3.3.0
              with:
                  github-tag: "v${{ env.MOD_VERSION }}"
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

                  github-generate-changelog: true

                  name: "Release v${{ env.MOD_VERSION }} for Minecraft ${{ env.MINECRAFT_VERSION }}"
                  version: "${{ env.MOD_VERSION }}"
                  version-type: release

                  files: "*/build/libs/skin_changer-{fabric,forge,neoforge,quilt,rift}-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}.jar"

                  java: "${{ env.JAVA_VERSION }}"

            - name: Publish Fabric (CurseForge/Modrinth)
              uses: Kir-Antipov/mc-publish@v3.3.0
              with:
                  curseforge-id: 378549
                  curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

                  modrinth-id: 5jVtTQGY
                  modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"

                  github-generate-changelog: true

                  name: "skin_changer-fabric-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}"
                  version: "${{ env.MOD_VERSION }}"
                  version-type: release

                  files: "fabric/build/libs/skin_changer-fabric-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}.jar"

                  java: "${{ env.JAVA_VERSION }}"

            - name: Publish NeoForge (CurseForge/Modrinth)
              uses: Kir-Antipov/mc-publish@v3.3.0
              with:
                  curseforge-id: 378549
                  curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

                  modrinth-id: 5jVtTQGY
                  modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"

                  github-generate-changelog: true

                  name: "skin_changer-neoforge-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}"
                  version: "${{ env.MOD_VERSION }}"
                  version-type: release

                  files: "neoforge/build/libs/skin_changer-neoforge-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}.jar"

                  java: "${{ env.JAVA_VERSION }}"
